### ISSUE TITLE
Admin layouts

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/layout_wildcard#20]
I installed on a site to test again and ran into an issue where the front end header was showing up on the back end when editing nodes, except without the front end theming (since it was using the admin theme). Looked a real mess! :smile: 

I think it must be related to match a `node/%` context (e.g. there is a layout with a node context and no other conditions on this site in question). 

Is this expected behavior? I'm not certain!

**Comment by bugfolder** [comment]
I'd need some further information to be able to answer if that behavior is expected, although I have my suspicions. Can you say the following:

- What is the path of a page that is acting up?
- On the layouts listing page (admin/structure/layouts), are there any layouts with paths that are similar? In fact, what are all the paths that appear on that listing page?

My suspicion is that this is [ancestor matching](https://github.com/backdrop-contrib/layout_wildcard/issues/19) run amok. In which case, it would be expected, albeit not _wanted_. Part of the roadmap task is figuring out what to do with ancestor matching in future versions to preserve backward compatibility, but provide better control over what paths get matched.

**Comment by laryn** [comment]
Here's how I reproduced on a test site (pretty simple actually):

- First test by editing a node with a different admin theme set (in this case Seven):
![no-node-context-layout](https://user-images.githubusercontent.com/871421/117833449-f816f200-b23b-11eb-8b7b-b7c3d11be5aa.png)
- Add (or enable) a Layout with a `node/%` context.
- Edit the same page again:
![with-node-context-layout](https://user-images.githubusercontent.com/871421/117833538-08c76800-b23c-11eb-8c4a-30c3172c068e.png)

**Comment by bugfolder** [comment]
Yes, that would be ancestor matching at work. What it does is [described here](https://github.com/backdrop-contrib/layout_wildcard/issues/19#issuecomment-828779445).

So when you go to edit the node, the path is (for example) `node/1/edit`. The ancestors are

* `node/1/%`
* `node/%/edit`
* `node/%/%`
* `node/1`
* `node/%`
* `node`

And so ancestor matching finds a match with the layout with path `node/%` and uses it. And that's what you're seeing.

So, it's behaving as designed. Just not as wanted.

Since taking over this module and working with layouts, I've come to the conclusion that ancestor matching is a pretty blunt instrument for adjusting layout choices because of the potential unexpected side effects from all the possible ancestors of a given path. At the very least, I think a future version of LW should have a checkbox to allow it to be turned off if desired. [Some thoughts here.](https://github.com/backdrop-contrib/layout_wildcard/issues/19#issuecomment-828781455)

**Comment by laryn** [comment]
Yes, makes sense. I'll close this for now since the roadmap includes this issue.

Workaround for the issue above (for now) -- add a visibility condition to the `node/%` layout(s) that URL path may not equal `node/*/edit`.
