### ISSUE TITLE
Documentation (Wiki) and support request

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/layout_wildcard#27]
Hi @bugfolder,

many thanks for this cool module.

I'm currently struggling with following description:

```
Ancestor matching
Use this layout if its path matches any ancestor of the requested path.
```
Maybe it's because I didn't have enough coffee, yet. but I simply can't figure out what that means.

Then tried to find additional info in the README:
```
Ancestor Matching
Check the "Ancestor matching" checkbox to turn on ancestor matching, in which the layout will be used if its primary path matches any ancestor of the request path.
```
... if its primary path matches any ancestor of the request path ...

What's the "primary path" and what's the "ancestor"?

Then I saw the link in "Additional documentation is located in the Wiki" - happily followed that link... but that documentation obviously doesn't exist. Help!

**Comment by bugfolder** [comment]
"Ancestor matching" is a feature that was already built into this module when I took it over. There's some explanation of the concept here: https://github.com/backdrop-contrib/layout_wildcard/issues/19#issuecomment-828779445

Now, I do realize that "read a comment in another issue" is not exactly best practice when it comes to documentation, so I'll add some documentation of it in a more reasonable location. But I do think that because it can have unexpected/not-obvious effects, I would discourage its usage going forward, in favor of the more explicit and precise "Alternative Paths". (And yes, that, too, should probably be in the documentation.)

**Comment by bugfolder** [comment]
Explanation now added to Wiki.

**Comment by indigoxela** [comment]
@bugfolder many thanks for the documentation. :tada: 

So, in fact "Ancestor matching" is as weird as I though? Will avoid to use it, and stick with "Alternative Paths" - which are self-explaining.
